name: Tag-based Release

on:
  push:
    tags:
      - 'v*' # 匹配以 "v" 开头的标签，例如 v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          src/.venv
        key: ${{ runner.os }}-deps-${{ hashFiles('src/config.sh') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Prepare APT cache directory
      run: |
        sudo mkdir -p /tmp/apt-cache
        sudo chown -R $USER:$USER /tmp/apt-cache

    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: /tmp/apt-cache
        key: ${{ runner.os }}-apt-${{ hashFiles('src/config.sh') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Configure APT cache
      run: |
        sudo tee /etc/apt/apt.conf.d/01cache <<EOF
        Dir::Cache "/tmp/apt-cache";
        Dir::Cache::archives "/tmp/apt-cache/archives";
        APT::Keep-Downloaded-Packages "true";
        EOF

    - name: Cache APT lists
      uses: actions/cache@v4
      with:
        path: |
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-lists-${{ hashFiles('src/config.sh') }}
        restore-keys: |
          ${{ runner.os }}-apt-lists-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Project
      run: |
        cd src
        chmod +x config.sh activate_env.sh
        ./config.sh
        source ./activate_env.sh
        python build.py -c -ninja ws63-liteos-app

    - name: Create GitHub Release
      id: create-release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          This release was automatically generated from tag ${{ github.ref_name }}.
        draft: false
        prerelease: ${{ contains(github.ref_name, 'rc') }}

    - name: Prepare Compiled Artifact
      run: |
        zip -r compiled-artifact.zip src/output/ws63/fwpkg
    
    - name: Upload Compiled Artifact
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: compiled-artifact.zip
        asset_name: compiled-artifact.zip
        asset_content_type: application/zip